name: Deploy Hugo site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'
          extended: true

      # 新增：安裝 Typst
      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
           typst_version: "latest"

      # 新增：安裝 Python (雖然 Ubuntu 內建，但宣告一下比較好)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build Site via Make
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
